age = input("Enter your age: ")
name = input("enter your username: ")
age = str(age) 
name = str(name)
print("your age is:", age)
print("your name is:", name)
print("Your personal information has been completed")